"""Train MyCNN and export data for the CNN 3D Loss Landscape panel.

Outputs generated by this script:
- models/numpy_mnist_cnn.npz                         final model weights from PRIMARY_LR
- models/artifacts/training_history.png              ordinary loss/accuracy chart
- models/artifacts/training_trace.npz                compact raw trace data for PRIMARY_LR
- models/artifacts/training_trace_meta.json          trace metadata
- static/assets/data/cnn/training_pca_trace.json     frontend PCA trajectory data
- static/assets/data/cnn/fc2_loss_surface.json       frontend FC2 loss-surface slice
- static/assets/data/cnn/lr_comparison_trace.json    multi-learning-rate trajectory comparison

Run from the CVClass project root, where models/data/train.csv exists.
"""

import json
import os
from datetime import datetime

import numpy as np
import pandas as pd
import matplotlib
matplotlib.use("Agg")  # command-line/server training should not block on plt.show()
import matplotlib.pyplot as plt
from sklearn.model_selection import train_test_split

from mycnn import MyCNN, FullyConnected


# ---------- configurable training / trace settings ----------
RANDOM_SEED = 2026
BATCH_SIZE = 64
TRAIN_EPOCHS = 3
PRIMARY_LR = 0.01

TRACE_ENABLED = True
TRACE_SAMPLE_EVERY = 25          # save one trace point every N batches
TRACE_SNAPSHOT_SCOPE = "fc2"     # recommended: fc2; all/both make files much larger
TRACE_VAL_SAMPLE_SIZE = 512       # validation subset used for trace-point val_loss / val_acc
SURFACE_GRID_SIZE = 31            # FC2 2D loss-surface grid; suggested 25~41
SURFACE_VAL_SAMPLE_SIZE = 512     # validation subset used for FC2 loss surface

# Frontend JSON results are written only here, per current project requirement.
ASSETS_DATA_DIR = "static/assets/data"

# Learning-rate comparison. Avoid very large lr first; NumPy CNN can diverge to NaN.
LR_COMPARE_ENABLED = True
LR_COMPARE_VALUES = [0.001, 0.01, 0.05, 0.1]
LR_COMPARE_EPOCHS = TRAIN_EPOCHS
LR_DIVERGENCE_LOSS_THRESHOLD = 20.0


def ensure_dir(path):
    if path:
        os.makedirs(path, exist_ok=True)


def to_jsonable(value):
    """Convert numpy scalars/arrays into JSON-compatible Python objects."""
    if isinstance(value, np.ndarray):
        return value.tolist()
    if isinstance(value, (np.floating, np.integer)):
        return value.item()
    if isinstance(value, dict):
        return {k: to_jsonable(v) for k, v in value.items()}
    if isinstance(value, list):
        return [to_jsonable(v) for v in value]
    return value


def write_json(path, obj):
    ensure_dir(os.path.dirname(path) or ".")
    with open(path, "w", encoding="utf-8") as f:
        json.dump(to_jsonable(obj), f, ensure_ascii=False, indent=2)


def softmax_cross_entropy_from_logits(logits, y_onehot):
    shifted = logits - np.max(logits, axis=1, keepdims=True)
    exp_scores = np.exp(shifted)
    probs = exp_scores / np.sum(exp_scores, axis=1, keepdims=True)
    loss = -np.sum(y_onehot * np.log(probs + 1e-8)) / logits.shape[0]
    acc = np.mean(np.argmax(probs, axis=1) == np.argmax(y_onehot, axis=1))
    return float(loss), float(acc)


def finite_number(value):
    try:
        value = float(value)
    except Exception:
        return False
    return np.isfinite(value)


def pca_directions(matrix, n_components=2):
    """Return PCA directions from a snapshot matrix [T, D]."""
    matrix = np.asarray(matrix, dtype=np.float64)
    if matrix.ndim != 2 or matrix.shape[0] < 2 or matrix.shape[1] == 0:
        dim = matrix.shape[1] if matrix.ndim == 2 and matrix.shape[1] else 2
        basis = np.zeros((n_components, dim), dtype=np.float64)
        for i in range(n_components):
            basis[i, i % dim] = 1.0
        center = matrix[0] if matrix.ndim == 2 and matrix.shape[0] else np.zeros(dim)
        return center, basis
    center = matrix.mean(axis=0)
    centered = matrix - center
    _, _, vt = np.linalg.svd(centered, full_matrices=False)
    basis = vt[:n_components]
    if basis.shape[0] < n_components:
        pad = np.zeros((n_components - basis.shape[0], basis.shape[1]))
        for i in range(pad.shape[0]):
            pad[i, i % pad.shape[1]] = 1.0
        basis = np.vstack([basis, pad])
    return center, basis


def make_pca_trace_json(history, out_path):
    """Build frontend training_pca_trace.json from trace rows and FC2 snapshots."""
    rows = history.get("trace_rows", [])
    fc2_snapshots = np.asarray(history.get("fc2_snapshots", np.empty((0, 0))), dtype=np.float64)
    if not rows or fc2_snapshots.size == 0:
        raise RuntimeError("没有可用的 trace_rows 或 fc2_snapshots，无法生成 PCA 轨迹")

    _, basis = pca_directions(fc2_snapshots, 2)
    final = fc2_snapshots[-1]
    coords = (fc2_snapshots - final) @ basis.T

    points = []
    for row, coord in zip(rows, coords):
        item = dict(row)
        item["pc1"] = float(coord[0])
        item["pc2"] = float(coord[1])
        item["loss"] = float(row.get("val_loss", row.get("train_loss", 0.0)))
        points.append(item)

    payload = {
        "success": True,
        "basis": "fc2_parameters_pca_final_centered",
        "description": "PCA trajectory is computed from saved FC2 parameter snapshots. PC1/PC2 are centered at the final FC2 parameter vector.",
        "num_points": len(points),
        "points": points,
        "generated_at": datetime.now().isoformat(timespec="seconds")
    }
    write_json(out_path, payload)
    return payload, basis, coords


def get_last_fc_layer(model):
    for layer in reversed(model.layers):
        if isinstance(layer, FullyConnected):
            return layer
    raise RuntimeError("模型中没有 FullyConnected 层")


def fc2_vector(layer):
    return np.concatenate([layer.weights.ravel(), layer.bias.ravel()]).astype(np.float64)


def set_fc2_vector(layer, vec):
    vec = np.asarray(vec, dtype=np.float64)
    w_size = layer.weights.size
    layer.weights = vec[:w_size].reshape(layer.weights.shape).copy()
    layer.bias = vec[w_size:].reshape(layer.bias.shape).copy()


def extract_fc2_input(model, X, batch_size=128):
    """Run all layers before the final FC layer once, so the FC2 surface can be scanned cheaply."""
    final_fc = get_last_fc_layer(model)
    features = []
    for start in range(0, X.shape[0], batch_size):
        x = X[start:start + batch_size]
        for layer in model.layers:
            if layer is final_fc:
                break
            x = layer.forward(x)
        if len(x.shape) > 2:
            x = x.reshape(x.shape[0], -1)
        features.append(x.copy())
    return np.vstack(features)


def make_fc2_loss_surface_json(model, history, X_val, y_val, basis, coords, out_path,
                               grid_size=SURFACE_GRID_SIZE, sample_size=SURFACE_VAL_SAMPLE_SIZE):
    """Generate a true 2D loss slice by varying only the final FC layer along two PCA directions."""
    rows = history.get("trace_rows", [])
    final_fc = get_last_fc_layer(model)
    base_vec = fc2_vector(final_fc)
    original_vec = base_vec.copy()

    if basis is None or basis.shape[0] < 2:
        _, basis = pca_directions(np.asarray(history.get("fc2_snapshots")), 2)
    direction_u = basis[0] / (np.linalg.norm(basis[0]) + 1e-12)
    direction_v = basis[1] / (np.linalg.norm(basis[1]) + 1e-12)

    if coords is None or len(coords) == 0:
        coords = np.zeros((len(rows), 2))
    alpha_min, alpha_max = float(np.min(coords[:, 0])), float(np.max(coords[:, 0]))
    beta_min, beta_max = float(np.min(coords[:, 1])), float(np.max(coords[:, 1]))

    def padded_range(lo, hi, min_width=1.0):
        width = max(hi - lo, min_width)
        center = (lo + hi) / 2
        return center - width * 0.65, center + width * 0.65

    alpha_min, alpha_max = padded_range(alpha_min, alpha_max)
    beta_min, beta_max = padded_range(beta_min, beta_max)
    alpha_values = np.linspace(alpha_min, alpha_max, grid_size)
    beta_values = np.linspace(beta_min, beta_max, grid_size)

    # Use a fixed validation subset; all convolutional features are precomputed once.
    X_surface = X_val[:min(sample_size, X_val.shape[0])]
    y_surface = y_val[:min(sample_size, y_val.shape[0])]
    fc2_input = extract_fc2_input(model, X_surface)

    loss_grid = []
    for beta in beta_values:
        row = []
        for alpha in alpha_values:
            vec = base_vec + alpha * direction_u + beta * direction_v
            w_size = final_fc.weights.size
            W = vec[:w_size].reshape(final_fc.weights.shape)
            b = vec[w_size:].reshape(final_fc.bias.shape)
            logits = fc2_input @ W + b
            loss, _ = softmax_cross_entropy_from_logits(logits, y_surface)
            row.append(loss)
        loss_grid.append(row)

    # Restore final trained parameters.
    set_fc2_vector(final_fc, original_vec)

    final_logits = fc2_input @ final_fc.weights + final_fc.bias
    final_loss, final_acc = softmax_cross_entropy_from_logits(final_logits, y_surface)

    # Important: this surface fixes all layers before FC2 at their final values.
    # Therefore the trajectory z-value drawn on this surface must also be evaluated
    # on the same FC2-only slice, instead of reusing historical full-network val_loss.
    trajectory_on_surface = []
    for row, coord in zip(rows, coords):
        alpha = float(coord[0])
        beta = float(coord[1])
        vec = base_vec + alpha * direction_u + beta * direction_v
        w_size = final_fc.weights.size
        W = vec[:w_size].reshape(final_fc.weights.shape)
        b = vec[w_size:].reshape(final_fc.bias.shape)
        logits = fc2_input @ W + b
        surface_loss, surface_acc = softmax_cross_entropy_from_logits(logits, y_surface)
        trajectory_on_surface.append({
            "alpha": alpha,
            "beta": beta,
            "loss": float(surface_loss),
            "surface_loss": float(surface_loss),
            "surface_acc": float(surface_acc),
            "history_loss": float(row.get("val_loss", row.get("loss", 0.0))),
            "step": int(row.get("step", 0))
        })

    payload = {
        "success": True,
        "description": "This is a true 2D slice of the validation loss where only the final FC2 parameters are changed along two PCA directions; other CNN layers are fixed.",
        "surface_coordinate": "alpha/beta are FC2 PCA coordinates centered at the final FC2 parameter vector; trajectory loss is re-evaluated on this same FC2-only slice.",
        "alpha_values": alpha_values.tolist(),
        "beta_values": beta_values.tolist(),
        "loss_grid": loss_grid,
        "final_point": {"alpha": 0.0, "beta": 0.0, "loss": float(final_loss), "acc": float(final_acc)},
        "trajectory_on_surface": trajectory_on_surface,
        "generated_at": datetime.now().isoformat(timespec="seconds")
    }
    write_json(out_path, payload)
    return payload


def save_raw_trace(history, out_dir="models"):
    ensure_dir(out_dir)
    ensure_dir(os.path.join(out_dir, "artifacts"))
    rows = history.get("trace_rows", [])
    fc2_snapshots = np.asarray(history.get("fc2_snapshots", np.empty((0, 0))), dtype=np.float32)
    theta_snapshots = np.asarray(history.get("theta_snapshots", np.empty((0, 0))), dtype=np.float32)

    def col(name, default=0.0):
        return np.asarray([row.get(name, default) for row in rows])

    trace_npz_path = os.path.join(out_dir, "artifacts", "training_trace.npz")
    np.savez_compressed(
        trace_npz_path,
        steps=col("step", 0),
        epochs=col("epoch", 0),
        batches=col("batch", 0),
        train_loss=col("train_loss", 0.0),
        val_loss=col("val_loss", 0.0),
        train_acc=col("train_acc", 0.0),
        val_acc=col("val_acc", 0.0),
        lr=col("lr", 0.0),
        grad_norm_total=col("grad_norm_total", 0.0),
        update_norm_total=col("update_norm_total", 0.0),
        conv1_grad_norm=col("conv1_grad_norm", 0.0),
        conv2_grad_norm=col("conv2_grad_norm", 0.0),
        fc1_grad_norm=col("fc1_grad_norm", 0.0),
        fc2_grad_norm=col("fc2_grad_norm", 0.0),
        fc2_snapshots=fc2_snapshots,
        theta_snapshots=theta_snapshots
    )
    meta = {
        "success": True,
        "trace_points": len(rows),
        "snapshot_scope": history.get("trace_config", {}).get("snapshot_scope", TRACE_SNAPSHOT_SCOPE),
        "fc2_snapshot_shape": list(fc2_snapshots.shape),
        "theta_snapshot_shape": list(theta_snapshots.shape),
        "generated_at": datetime.now().isoformat(timespec="seconds")
    }
    meta_path = os.path.join(out_dir, "artifacts", "training_trace_meta.json")
    write_json(meta_path, meta)
    return trace_npz_path, meta_path


def sanitize_history_for_compare(history, loss_threshold=LR_DIVERGENCE_LOSS_THRESHOLD):
    """Keep only finite trace rows and aligned FC2 snapshots for LR comparison."""
    rows = list(history.get("trace_rows", []))
    snaps = np.asarray(history.get("fc2_snapshots", np.empty((0, 0))), dtype=np.float64)
    valid_rows = []
    valid_snaps = []
    status = "ok"
    stop_reason = ""
    for idx, row in enumerate(rows):
        if idx >= len(snaps):
            break
        loss = float(row.get("val_loss", row.get("loss", np.nan)))
        snap = snaps[idx]
        if (not np.isfinite(loss)) or np.any(~np.isfinite(snap)):
            status = "diverged"
            stop_reason = "nan_or_inf"
            break
        if abs(loss) > loss_threshold:
            status = "diverged"
            stop_reason = f"loss>{loss_threshold}"
            # keep the first large-loss point so the front end can mark divergence
            valid_rows.append(row)
            valid_snaps.append(snap)
            break
        valid_rows.append(row)
        valid_snaps.append(snap)
    return valid_rows, np.asarray(valid_snaps, dtype=np.float64), status, stop_reason


def train_one_lr(lr, X_train, y_train, X_val, y_val, epochs=TRAIN_EPOCHS, seed=RANDOM_SEED):
    """Train a fresh model with fixed initialization/shuffle seed for fair LR comparison."""
    np.random.seed(seed)
    model = MyCNN.model()
    history = model.train(
        X_train=X_train, y_train=y_train,
        X_val=X_val, y_val=y_val,
        batch_size=BATCH_SIZE, epochs=epochs, learning_rate=lr,
        trace_config={
            "enabled": TRACE_ENABLED,
            "sample_every": TRACE_SAMPLE_EVERY,
            "snapshot_scope": "fc2",
            "val_sample_size": TRACE_VAL_SAMPLE_SIZE
        }
    )
    return model, history


def make_lr_comparison_json(histories_by_lr, primary_lr, out_path):
    """Create a shared-PCA multi-learning-rate trajectory file for the frontend."""
    cleaned = {}
    all_snaps = []
    primary_final = None

    for lr, history in histories_by_lr.items():
        rows, snaps, status, stop_reason = sanitize_history_for_compare(history)
        cleaned[float(lr)] = {
            "rows": rows,
            "snaps": snaps,
            "status": status,
            "stop_reason": stop_reason
        }
        if snaps.size > 0:
            all_snaps.append(snaps)
        if abs(float(lr) - float(primary_lr)) < 1e-12 and snaps.size > 0:
            primary_final = snaps[-1]

    if not all_snaps:
        raise RuntimeError("没有可用于学习率对比的参数快照")

    all_matrix = np.vstack(all_snaps)
    _, basis = pca_directions(all_matrix, 2)
    origin = primary_final if primary_final is not None else all_matrix[-1]

    series = []
    for lr in sorted(cleaned.keys()):
        item = cleaned[lr]
        rows = item["rows"]
        snaps = item["snaps"]
        coords = (snaps - origin) @ basis.T if snaps.size else np.empty((0, 2))
        points = []
        for row, coord in zip(rows, coords):
            loss = float(row.get("val_loss", row.get("loss", row.get("train_loss", 0.0))))
            points.append({
                "step": int(row.get("step", 0)),
                "epoch": int(row.get("epoch", 0)),
                "batch": int(row.get("batch", 0)),
                "pc1": float(coord[0]),
                "pc2": float(coord[1]),
                "loss": loss,
                "train_loss": float(row.get("train_loss", loss)),
                "val_loss": float(row.get("val_loss", loss)),
                "train_acc": float(row.get("train_acc", 0.0)),
                "val_acc": float(row.get("val_acc", 0.0)),
                "lr": float(lr),
                "grad_norm_total": float(row.get("grad_norm_total", 0.0)),
                "update_norm_total": float(row.get("update_norm_total", 0.0))
            })
        label = f"lr={lr:g}"
        if lr < primary_lr:
            lr_type = "slow"
        elif abs(lr - primary_lr) < 1e-12:
            lr_type = "primary"
        else:
            lr_type = "fast"
        series.append({
            "lr": float(lr),
            "label": label,
            "type": lr_type,
            "status": item["status"],
            "stop_reason": item["stop_reason"],
            "num_points": len(points),
            "points": points
        })

    payload = {
        "success": True,
        "description": "Learning-rate comparison trajectories are projected with one shared PCA basis computed from all FC2 snapshots. Coordinates are centered at the primary model's final FC2 parameters.",
        "primary_lr": float(primary_lr),
        "learning_rates": [float(lr) for lr in sorted(cleaned.keys())],
        "basis": "shared_fc2_parameters_pca_primary_final_centered",
        "series": series,
        "generated_at": datetime.now().isoformat(timespec="seconds")
    }
    write_json(out_path, payload)
    return payload


def load_mnist_csv():
    train = pd.read_csv("models/data/train.csv")
    train_X = train.drop(["label"], axis=1)
    train_y = train["label"]

    classes = np.unique(train_y)  # label encoding
    class_dict = dict(zip(classes, range(len(classes))))
    Y_int = train_y.map(class_dict)
    train_y = np.eye(len(classes))[Y_int]
    train_X = train_X / 255.0
    train_X = train_X.values.reshape(-1, 1, 28, 28)

    X_train, X_test, y_train, y_test = train_test_split(train_X, train_y, test_size=0.1, random_state=42)
    X_train, X_val, y_train, y_val = train_test_split(X_train, y_train, test_size=0.1, random_state=42)
    return X_train, X_val, X_test, y_train, y_val, y_test


def save_history_figures(history, model, X_test, y_test):
    ensure_dir("models/artifacts")
    history_fig = plt.figure(figsize=(12, 4))
    plt.subplot(1, 2, 1)
    plt.plot(history["train_loss"], label="train_loss")
    plt.plot(history["val_loss"], label="val_loss")
    plt.title("Loss")
    plt.legend()

    plt.subplot(1, 2, 2)
    plt.plot(history["train_acc"], label="train_acc")
    plt.plot(history["val_acc"], label="val_acc")
    plt.title("Accuracy")
    plt.legend()
    plt.tight_layout()
    history_fig.savefig("models/artifacts/training_history.png", dpi=160)
    plt.close(history_fig)

    num_samples = min(5, len(y_test))
    indices = np.random.choice(len(y_test), num_samples, replace=False)
    X_samples = X_test[indices]
    y_samples = y_test[indices]
    predictions = model.predict(X_samples)
    y_samples_labels = np.argmax(y_samples, axis=1)

    prediction_fig = plt.figure(figsize=(15, 3))
    for i in range(num_samples):
        plt.subplot(1, num_samples, i + 1)
        plt.imshow(X_samples[i, 0], cmap="gray", vmin=0, vmax=1)
        plt.title(f"True: {y_samples_labels[i]}\nPred: {predictions[i]}")
        plt.axis("off")
    plt.tight_layout()
    prediction_fig.savefig("models/artifacts/predictions.png", dpi=160)
    plt.close(prediction_fig)


def main():
    ensure_dir("models")
    ensure_dir("models/artifacts")
    ensure_dir(ASSETS_DATA_DIR)

    X_train, X_val, X_test, y_train, y_val, y_test = load_mnist_csv()
    print(f"训练集大小: {X_train.shape}")
    print(f"验证集大小: {X_val.shape}")
    print(f"测试集大小: {X_test.shape}")

    print(f"开始主训练：lr={PRIMARY_LR}，并保存 Loss Landscape 所需轨迹数据...")
    np.random.seed(RANDOM_SEED)
    model = MyCNN.model()
    history = model.train(
        X_train=X_train, y_train=y_train,
        X_val=X_val, y_val=y_val,
        batch_size=BATCH_SIZE, epochs=TRAIN_EPOCHS, learning_rate=PRIMARY_LR,
        trace_config={
            "enabled": TRACE_ENABLED,
            "sample_every": TRACE_SAMPLE_EVERY,
            "snapshot_scope": TRACE_SNAPSHOT_SCOPE,
            "val_sample_size": TRACE_VAL_SAMPLE_SIZE
        }
    )

    print("在测试集上评估主模型...")
    test_loss, test_acc = model.evaluate(X_test, y_test)
    print(f"测试集上的损失: {test_loss:.4f}, 准确率: {test_acc:.4f}")

    weight_path = "models/numpy_mnist_cnn.npz"
    model.save_params(weight_path)
    print(f"模型参数已保存到: {weight_path}")

    if TRACE_ENABLED:
        print("正在保存主训练 raw trace npz/meta...")
        trace_npz_path, trace_meta_path = save_raw_trace(history, "models")
        print(f"训练轨迹已保存: {trace_npz_path}, {trace_meta_path}")

        print("正在生成主训练 PCA 轨迹 JSON...")
        pca_path = os.path.join(ASSETS_DATA_DIR, "training_pca_trace.json")
        pca_payload, pca_basis, pca_coords = make_pca_trace_json(history, pca_path)
        print(f"PCA 轨迹已保存到 {pca_path}")

        print("正在生成主训练 FC2 二维真实 loss surface JSON...")
        surface_path = os.path.join(ASSETS_DATA_DIR, "fc2_loss_surface.json")
        make_fc2_loss_surface_json(
            model, history, X_val, y_val, pca_basis, pca_coords,
            surface_path,
            grid_size=SURFACE_GRID_SIZE,
            sample_size=SURFACE_VAL_SAMPLE_SIZE
        )
        print(f"FC2 loss surface 已保存到 {surface_path}")

        if LR_COMPARE_ENABLED:
            print("开始学习率对比训练...")
            histories_by_lr = {float(PRIMARY_LR): history}
            for lr in LR_COMPARE_VALUES:
                lr = float(lr)
                if abs(lr - float(PRIMARY_LR)) < 1e-12:
                    continue
                print(f"\n[LR Compare] 训练 lr={lr:g}")
                try:
                    _, lr_history = train_one_lr(
                        lr, X_train, y_train, X_val, y_val,
                        epochs=LR_COMPARE_EPOCHS,
                        seed=RANDOM_SEED
                    )
                    histories_by_lr[lr] = lr_history
                except FloatingPointError as exc:
                    print(f"lr={lr:g} 出现数值错误，跳过后续：{exc}")
                except Exception as exc:
                    print(f"lr={lr:g} 训练失败，跳过该轨迹：{exc}")

            lr_compare_path = os.path.join(ASSETS_DATA_DIR, "lr_comparison_trace.json")
            make_lr_comparison_json(histories_by_lr, PRIMARY_LR, lr_compare_path)
            print(f"学习率对比轨迹已保存到 {lr_compare_path}")

    save_history_figures(history, model, X_test, y_test)
    print("训练与可视化数据导出完成。")


if __name__ == "__main__":
    main()
